// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"context"
)

type Querier interface {
	CheckUserExists(ctx context.Context, arg CheckUserExistsParams) (bool, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteRefreshToken(ctx context.Context, username string) (Session, error)
	GetToken(ctx context.Context, username string) (Session, error)
	IsLoggedIn(ctx context.Context, username string) (bool, error)
	LoginUser(ctx context.Context, username string) (User, error)
}

var _ Querier = (*Queries)(nil)
