database:
  url: postgresql://root:@localhost:26257/userstore?sslmode=disable
  file: file://internal/constants/db/migration
  murl: cockroachdb://root:@localhost:26257/userstore?sslmode=disable
server:
  port: 8000
  timeout: 30s
secret_key: encryptpasswordd
