version: "2"
sql:
  - schema: "../internal/constants/db/migration"
    queries: "../internal/constants/db/queries"
    engine: "postgresql"
    gen:
      go:
        package: "db"
        out: "../internal/constants/db/sqlc"
        sql_package: "pgx/v5"
        emit_json_tags: true
        emit_interface: true
        emit_empty_slices: true
