name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      cockroachdb:
        image: cockroachdb/cockroach:latest
        ports:
          - 26257:26257
          - 8080:8080
        # options: --env=COCKROACH_DATABASE=mydb --env=COCKROACH_USER=root --env=COCKROACH_INSECURE=true
        # Set the health check to wait until CockroachDB is ready
        # healthcheck:
        #   test: ["CMD-SHELL", "nc -z localhost 26257"]
        #   interval: 10s
        #   timeout: 5s
        #   retries: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install dependencies
        run: |
          go get -v -t -d ./...
          go install github.com/cucumber/godog/cmd/godog@latest

      - name: Wait for CockroachDB to be ready
        run: |
          until nc -z localhost 26257; do
            echo "Waiting for CockroachDB...";
            sleep 1;
          done

      - name: Run tests
        env:
          DATABASE_URL: postgresql://root@localhost:26257/userstore?sslmode=disable
        run: go test ./...

      - name: Run GoDog tests
        env:
          DATABASE_URL: postgresql://root@localhost:26257/userstore?sslmode=disable
        run: godog

      - name: Run GolangCI-Lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.45.0
          golangci-lint run
