name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Start a single CockroachDB instance with docker
        run: |
          docker pull cockroachdb/cockroach:latest
          docker run -d --name roach --hostname roach -p 26257:26257 -p 8080:8080 cockroachdb/cockroach:latest start-single-node --insecure
          sudo apt update && sudo apt install wait-for-it -y
          wait-for-it -h localhost -p 26257
          docker exec roach bash -c 'echo "CREATE DATABASE userstore;" | cockroach sql --insecure'

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.1"

      # - name: Cache Go modules
      #   uses: actions/cache@v3
      #   with:
      #     path: ~/go/pkg/mod
      #     key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
      #     restore-keys: |
      #       ${{ runner.os }}-go-

      - name: Install dependencies
        run: |
          go get -v -t -d ./...
          go install github.com/cucumber/godog/cmd/godog@latest

      - name: Make Migration
        run: make migrate-up

      - name: Run GoDog tests
        env:
          DATABASE_URL: postgresql://root@localhost:26257/mydb?sslmode=disable
        run: make test
