name: ci-test

on:
  push:
    branches:
      - main
    pull_request:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      cockroach:
        image: cockroachdb/cockroach:latest
        # command: start-single-node --insecure
        ports:
          - 26257:26257
          - 8080:8080
        # env:
        #   COCKROACH_DATABASE: userstore
        #   COCKROACH_USER: root
        #   COCKROACH_INSECURE: true
        # options: >-
        #   --health-cmd pg_isready -h localhost -p 26257
        #   --health-interval 10s
        #   --health-timeout 5s
        #   --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22.1"
      - name: Install CockroachDB
        run: |
          sudo apt-get update
          sudo apt-get install -y cockroachdb

      - name: Start CockroachDB single-node cluster
        run: |
          cockroach start-single-node --insecure --background --listen-addr=localhost

      - name: Install dependencies
        run: |
          go get -v -t -d ./...
          go install github.com/cucumber/godog/cmd/godog@latest

      # - name: Run tests
      #   env:
      #     DATABASE_URL: postgresql://root@localhost:26257/mydb?sslmode=disable
      #   run: go test ./...
